### ISSUE TITLE
usage guidance

### ISSUE THREAD

**Issue by JunMa11** [MECLabTUDA/MUKNO#2]
Dear @MECLabTUDA ,

Thanks for sharing the code.

Could you add a `ReadMe` file about how to use the code?

Best,
Jun

**Comment by MECLabTUDA** [comment]
Dear JunMa11,

thank you for your interest in the code base.
We updated the wiki entry und also put the information in a readme file.

If there are any further issues, please contact us again!

Best,
Johannes

**Comment by JunMa11** [comment]
Got it. Thank you very much.
